import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import VideoCard from '../components/VideoCard';
import requests from "../utils/requests";


export default function Home({results}) {
  return (
    <div >
      <Head>
        <title>Movie Streamer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <VideoCard results={results}/>
      
    </div>
  )
}

export async function getServerSideProps(context) {

  const request = await fetch(
    `https://api.themoviedb.org/3/${
      requests.fetchMovies.url
    }`
  ).then(res => res.json());

  return {
    props: {
      results:request.results
    }
  }
}
